### ISSUE TITLE
채팅 레이아웃 v2 적용

### ISSUE THREAD

**Issue by yjc2021** [zzalmyu/zzalmyu-frontend#82]
## 어떤 기능인가요?

변경된 채팅 레이아웃을 프로젝트에 적용합니다

## 작업 상세 내용

- _layout-with-chat.tsx 레이아웃 수정

## 참고할만한 자료(선택)
![image](https://github.com/zzalmyu/zzalmyu-frontend/assets/88219703/0c18e066-5631-465c-8a9d-4fb970139704)

**Comment by thalassophilia** [comment]
순수한 궁금증인데, `부끄러운 짤용이` 같은 닉네임은 어떻게 결정되나용?

**Comment by yjc2021** [comment]
WebSocket 연결 성공 시 BE에서 형용사 table과 이름 table에서 각각 무작위 항목을 매칭하여 이름을 만들어 배정해줍니다!
